[package]
name = "render_gl_derive"
version = "0.1.0"
authors = ["kristoncosta"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "0.6.13"
syn = "0.15.42"
proc-macro2 = "0.4.30"

[lib]
proc-macro = true
